//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gotovoe_prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приход денег.
    /// </summary>
    // *** Start programmer edit section *** (ПриходДенег CustomAttributes)

    // *** End programmer edit section *** (ПриходДенег CustomAttributes)
    [AutoAltered()]
    [Caption("Приход денег")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриходДенегE", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "РасходПриход as \'Расход/приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'",
            "Финансисты as \'Финансисты\'",
            "Финансисты.ФИО as \'ФИО финансиста\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО клиента\'"}, Hidden=new string[] {
            "Финансисты.ФИО",
            "Клиенты.ФИО"})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "ПереченьУслуг", "ПереченьУслугE", true, "", "Перечень услуг", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "ПереченьТоваров", "ПереченьТоваровE", true, "", "Перечень товаров", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПриходДенегE", "Финансисты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПриходДенегE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПриходДенегL", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "РасходПриход as \'Расход/приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'",
            "Финансисты.ФИО as \'ФИО финансиста\'",
            "Клиенты.ФИО as \'ФИО клиента\'"})]
    public class ПриходДенег : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата;
        
        private IIS.Gotovoe_prilozhenie.РасходПриход fРасходПриход;
        
        private IIS.Gotovoe_prilozhenie.Тип fТип;
        
        private double fСумма;
        
        private IIS.Gotovoe_prilozhenie.Финансисты fФинансисты;
        
        private IIS.Gotovoe_prilozhenie.Клиенты fКлиенты;
        
        private IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьТоваров fПереченьТоваров;
        
        private IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьУслуг fПереченьУслуг;
        
        // *** Start programmer edit section *** (ПриходДенег CustomMembers)

        // *** End programmer edit section *** (ПриходДенег CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ID CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Get start)

                // *** End programmer edit section *** (ПриходДенег.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (ПриходДенег.ID Get end)

                // *** End programmer edit section *** (ПриходДенег.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Set start)

                // *** End programmer edit section *** (ПриходДенег.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (ПриходДенег.ID Set end)

                // *** End programmer edit section *** (ПриходДенег.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Дата CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Get start)

                // *** End programmer edit section *** (ПриходДенег.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПриходДенег.Дата Get end)

                // *** End programmer edit section *** (ПриходДенег.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Set start)

                // *** End programmer edit section *** (ПриходДенег.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПриходДенег.Дата Set end)

                // *** End programmer edit section *** (ПриходДенег.Дата Set end)
            }
        }
        
        /// <summary>
        /// РасходПриход.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.РасходПриход CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.РасходПриход CustomAttributes)
        public virtual IIS.Gotovoe_prilozhenie.РасходПриход РасходПриход
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Get start)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Get start)
                IIS.Gotovoe_prilozhenie.РасходПриход result = this.fРасходПриход;
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Get end)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Set start)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Set start)
                this.fРасходПриход = value;
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Set end)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Сумма CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Тип CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Тип CustomAttributes)
        public virtual IIS.Gotovoe_prilozhenie.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Тип Get start)

                // *** End programmer edit section *** (ПриходДенег.Тип Get start)
                IIS.Gotovoe_prilozhenie.Тип result = this.fТип;
                // *** Start programmer edit section *** (ПриходДенег.Тип Get end)

                // *** End programmer edit section *** (ПриходДенег.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Тип Set start)

                // *** End programmer edit section *** (ПриходДенег.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ПриходДенег.Тип Set end)

                // *** End programmer edit section *** (ПриходДенег.Тип Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Gotovoe_prilozhenie.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Get start)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Get start)
                IIS.Gotovoe_prilozhenie.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Get end)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Set start)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Set end)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Финансисты CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Финансисты CustomAttributes)
        [PropertyStorage(new string[] {
                "Финансисты"})]
        [NotNull()]
        public virtual IIS.Gotovoe_prilozhenie.Финансисты Финансисты
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Финансисты Get start)

                // *** End programmer edit section *** (ПриходДенег.Финансисты Get start)
                IIS.Gotovoe_prilozhenie.Финансисты result = this.fФинансисты;
                // *** Start programmer edit section *** (ПриходДенег.Финансисты Get end)

                // *** End programmer edit section *** (ПриходДенег.Финансисты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Финансисты Set start)

                // *** End programmer edit section *** (ПриходДенег.Финансисты Set start)
                this.fФинансисты = value;
                // *** Start programmer edit section *** (ПриходДенег.Финансисты Set end)

                // *** End programmer edit section *** (ПриходДенег.Финансисты Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ПереченьТоваров CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ПереченьТоваров CustomAttributes)
        public virtual IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьТоваров ПереченьТоваров
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ПереченьТоваров Get start)

                // *** End programmer edit section *** (ПриходДенег.ПереченьТоваров Get start)
                if ((this.fПереченьТоваров == null))
                {
                    this.fПереченьТоваров = new IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьТоваров(this);
                }
                IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьТоваров result = this.fПереченьТоваров;
                // *** Start programmer edit section *** (ПриходДенег.ПереченьТоваров Get end)

                // *** End programmer edit section *** (ПриходДенег.ПереченьТоваров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ПереченьТоваров Set start)

                // *** End programmer edit section *** (ПриходДенег.ПереченьТоваров Set start)
                this.fПереченьТоваров = value;
                // *** Start programmer edit section *** (ПриходДенег.ПереченьТоваров Set end)

                // *** End programmer edit section *** (ПриходДенег.ПереченьТоваров Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ПереченьУслуг CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ПереченьУслуг CustomAttributes)
        public virtual IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьУслуг ПереченьУслуг
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ПереченьУслуг Get start)

                // *** End programmer edit section *** (ПриходДенег.ПереченьУслуг Get start)
                if ((this.fПереченьУслуг == null))
                {
                    this.fПереченьУслуг = new IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьУслуг(this);
                }
                IIS.Gotovoe_prilozhenie.DetailArrayOfПереченьУслуг result = this.fПереченьУслуг;
                // *** Start programmer edit section *** (ПриходДенег.ПереченьУслуг Get end)

                // *** End programmer edit section *** (ПриходДенег.ПереченьУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ПереченьУслуг Set start)

                // *** End programmer edit section *** (ПриходДенег.ПереченьУслуг Set start)
                this.fПереченьУслуг = value;
                // *** Start programmer edit section *** (ПриходДенег.ПереченьУслуг Set end)

                // *** End programmer edit section *** (ПриходДенег.ПереченьУслуг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриходДенегE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегE", typeof(IIS.Gotovoe_prilozhenie.ПриходДенег));
                }
            }
            
            /// <summary>
            /// "ПриходДенегL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегL", typeof(IIS.Gotovoe_prilozhenie.ПриходДенег));
                }
            }
        }
    }
}
